services:
  joystick:
    image: joystick_ros2:latest
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
    user: "${UID}:${GID}"
    environment:
      - HOME=/tmp
    stdin_open: true
    tty: true
    command: ros2 launch joy_to_cmd_vel joy_to_cmd_vel_launch.py