services:
  joystick:
    image: joystick_ros2:latest
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/input/js0
    command: ros2 launch joy_to_cmd_vel joy_to_cmd_vel_launch.py